### ISSUE TITLE
shorthand notation for pipelines

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3sugar#5]
the current rules for pipelines might cosiderably shorten the amount of code in scripts and slides for users

1) string id --> PipeOp retrieved from dict with given id, in its defaults
2) Helper function: po = function(id, …) mlr_pipeops$get(id, …)
3) Helper function lrn = function(learner, id, …) mlr_pipeops$get("learner", learner = mlr_learners$get(learner, ...), id = id)
4) learner object --> PipeopLearner$new(learner = learner)

I think these are really helpful (although I am unsure whether I really need rule 4), probably not.

@mllg doesnt really like them and thinks this is too much sugar and not needed

we agreed we document the proposal here, wait a bit and ask more persons

**Comment by mb706** [comment]
The `po` is now in mlr3pipelines [here](https://github.com/mlr-org/mlr3pipelines/commit/da1392607e3b6d6bb38106de92e350fb34d58f95), the autoconversion is mlr-org/mlr3pipelines#177 and mlr-org/mlr3pipelines#185
